# Generated by Django 2.1.2 on 2018-12-16 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessoninfo',
            options={'verbose_name': '章节信息', 'verbose_name_plural': '章节信息'},
        ),
    ]
