# Generated by Django 2.1.2 on 2018-12-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20181216_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='category',
            field=models.CharField(choices=[('frontend', '前端开发'), ('backend', '后端开发')], max_length=10, verbose_name='课程类别'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='level',
            field=models.CharField(choices=[('senior', '高级'), ('middle', '中级'), ('junior', '初级')], default='junior', max_length=10, verbose_name='课程难度'),
        ),

        migrations.AddField(
            model_name='courseinfo',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='是否轮播'),
        ),


    ]
