# Generated by Django 2.1.2 on 2018-12-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20181206_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlove',
            name='love_type',
            field=models.IntegerField(choices=[(1, 'course'), (2, 'teacher'), (3, 'org')], verbose_name='收藏类别'),
        ),
    ]
